[package]
name = "platformer"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
wasm-bindgen = "0.2"
bevy_rapier2d = { version = "0.12.1", features = [ "wasm-bindgen" ] }
rand = "0.8.4"
getrandom = { version = "0.2", features = ["js"] }
bevy = "0.6"
